import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";
import { Button } from "../components/ui-bx/button";


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>POC Manifesto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">POC Manifesto</a>
        </h1>
        <button type="button" className="btn btn-secondary text-white">Secondary</button>

        <Button onClick={() => console.log("Check button")} size="lg">
          Check Button
        </Button>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
      </main>
    </div>
  );
};

export default Home;
